# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTabWidget, QTableWidget, QTableWidgetItem, QVBoxLayout,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(700, 680)
        Form.setMinimumSize(QSize(700, 0))
        Form.setMaximumSize(QSize(700, 100000))
        self.horizontalLayout = QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(0, 0))
        self.tabWidget.setMaximumSize(QSize(16777215, 16777215))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"QTabBar::tab {\n"
"    height: 35px;   /* \u8bbe\u7f6e\u6807\u7b7e\u7684\u9ad8\u5ea6 */\n"
"    font-size: 14px; /* \u5b57\u4f53\u8c03\u5927\u4e00\u70b9\u663e\u5f97\u66f4\u534f\u8c03 */\n"
"}")
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.verticalLayout_5 = QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setStyleSheet(u"background-color: #fff2bc;\n"
"border:2px solid black;\n"
"padding:8px;\n"
"color:#593800;")

        self.verticalLayout_5.addWidget(self.label)

        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(0, 0))

        self.verticalLayout_5.addWidget(self.label_2)

        self.comboBox_2 = QComboBox(self.tab)
        self.comboBox_2.setObjectName(u"comboBox_2")

        self.verticalLayout_5.addWidget(self.comboBox_2)

        self.pushButton_5 = QPushButton(self.tab)
        self.pushButton_5.setObjectName(u"pushButton_5")

        self.verticalLayout_5.addWidget(self.pushButton_5)

        self.pushButton = QPushButton(self.tab)
        self.pushButton.setObjectName(u"pushButton")

        self.verticalLayout_5.addWidget(self.pushButton)

        self.pushButton_2 = QPushButton(self.tab)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.verticalLayout_5.addWidget(self.pushButton_2)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")

        self.horizontalLayout_11.addWidget(self.label_15)

        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")

        self.horizontalLayout_11.addWidget(self.label_16)


        self.verticalLayout_5.addLayout(self.horizontalLayout_11)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.comboBox_15 = QComboBox(self.tab)
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.setObjectName(u"comboBox_15")

        self.horizontalLayout_3.addWidget(self.comboBox_15)

        self.lineEdit_14 = QLineEdit(self.tab)
        self.lineEdit_14.setObjectName(u"lineEdit_14")

        self.horizontalLayout_3.addWidget(self.lineEdit_14)

        self.comboBox_16 = QComboBox(self.tab)
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.setObjectName(u"comboBox_16")

        self.horizontalLayout_3.addWidget(self.comboBox_16)

        self.lineEdit_15 = QLineEdit(self.tab)
        self.lineEdit_15.setObjectName(u"lineEdit_15")

        self.horizontalLayout_3.addWidget(self.lineEdit_15)


        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.label_19 = QLabel(self.tab)
        self.label_19.setObjectName(u"label_19")

        self.horizontalLayout_13.addWidget(self.label_19)

        self.label_20 = QLabel(self.tab)
        self.label_20.setObjectName(u"label_20")

        self.horizontalLayout_13.addWidget(self.label_20)


        self.verticalLayout_5.addLayout(self.horizontalLayout_13)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.comboBox_19 = QComboBox(self.tab)
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.setObjectName(u"comboBox_19")

        self.horizontalLayout_6.addWidget(self.comboBox_19)

        self.lineEdit_18 = QLineEdit(self.tab)
        self.lineEdit_18.setObjectName(u"lineEdit_18")

        self.horizontalLayout_6.addWidget(self.lineEdit_18)

        self.comboBox_20 = QComboBox(self.tab)
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.setObjectName(u"comboBox_20")

        self.horizontalLayout_6.addWidget(self.comboBox_20)

        self.lineEdit_19 = QLineEdit(self.tab)
        self.lineEdit_19.setObjectName(u"lineEdit_19")

        self.horizontalLayout_6.addWidget(self.lineEdit_19)


        self.verticalLayout_5.addLayout(self.horizontalLayout_6)

        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.label_21 = QLabel(self.tab)
        self.label_21.setObjectName(u"label_21")

        self.horizontalLayout_14.addWidget(self.label_21)

        self.label_22 = QLabel(self.tab)
        self.label_22.setObjectName(u"label_22")

        self.horizontalLayout_14.addWidget(self.label_22)


        self.verticalLayout_5.addLayout(self.horizontalLayout_14)

        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.comboBox_21 = QComboBox(self.tab)
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.setObjectName(u"comboBox_21")

        self.horizontalLayout_7.addWidget(self.comboBox_21)

        self.lineEdit_20 = QLineEdit(self.tab)
        self.lineEdit_20.setObjectName(u"lineEdit_20")

        self.horizontalLayout_7.addWidget(self.lineEdit_20)

        self.comboBox_22 = QComboBox(self.tab)
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.setObjectName(u"comboBox_22")

        self.horizontalLayout_7.addWidget(self.comboBox_22)

        self.lineEdit_22 = QLineEdit(self.tab)
        self.lineEdit_22.setObjectName(u"lineEdit_22")

        self.horizontalLayout_7.addWidget(self.lineEdit_22)


        self.verticalLayout_5.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.label_25 = QLabel(self.tab)
        self.label_25.setObjectName(u"label_25")

        self.horizontalLayout_15.addWidget(self.label_25)

        self.label_26 = QLabel(self.tab)
        self.label_26.setObjectName(u"label_26")

        self.horizontalLayout_15.addWidget(self.label_26)


        self.verticalLayout_5.addLayout(self.horizontalLayout_15)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.comboBox_23 = QComboBox(self.tab)
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.setObjectName(u"comboBox_23")

        self.horizontalLayout_8.addWidget(self.comboBox_23)

        self.lineEdit_23 = QLineEdit(self.tab)
        self.lineEdit_23.setObjectName(u"lineEdit_23")

        self.horizontalLayout_8.addWidget(self.lineEdit_23)

        self.comboBox_24 = QComboBox(self.tab)
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.setObjectName(u"comboBox_24")

        self.horizontalLayout_8.addWidget(self.comboBox_24)

        self.lineEdit_24 = QLineEdit(self.tab)
        self.lineEdit_24.setObjectName(u"lineEdit_24")

        self.horizontalLayout_8.addWidget(self.lineEdit_24)


        self.verticalLayout_5.addLayout(self.horizontalLayout_8)

        self.horizontalLayout_16 = QHBoxLayout()
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.label_27 = QLabel(self.tab)
        self.label_27.setObjectName(u"label_27")

        self.horizontalLayout_16.addWidget(self.label_27)

        self.label_28 = QLabel(self.tab)
        self.label_28.setObjectName(u"label_28")

        self.horizontalLayout_16.addWidget(self.label_28)


        self.verticalLayout_5.addLayout(self.horizontalLayout_16)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.comboBox_25 = QComboBox(self.tab)
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.setObjectName(u"comboBox_25")

        self.horizontalLayout_9.addWidget(self.comboBox_25)

        self.lineEdit_25 = QLineEdit(self.tab)
        self.lineEdit_25.setObjectName(u"lineEdit_25")

        self.horizontalLayout_9.addWidget(self.lineEdit_25)

        self.comboBox_26 = QComboBox(self.tab)
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.setObjectName(u"comboBox_26")

        self.horizontalLayout_9.addWidget(self.comboBox_26)

        self.lineEdit_26 = QLineEdit(self.tab)
        self.lineEdit_26.setObjectName(u"lineEdit_26")

        self.horizontalLayout_9.addWidget(self.lineEdit_26)


        self.verticalLayout_5.addLayout(self.horizontalLayout_9)

        self.pushButton_11 = QPushButton(self.tab)
        self.pushButton_11.setObjectName(u"pushButton_11")

        self.verticalLayout_5.addWidget(self.pushButton_11)

        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")

        self.verticalLayout_5.addWidget(self.label_7)

        self.label_30 = QLabel(self.tab)
        self.label_30.setObjectName(u"label_30")

        self.verticalLayout_5.addWidget(self.label_30)

        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")

        self.verticalLayout_5.addWidget(self.label_8)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayout = QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(90, 16777215))
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_3)

        self.lineEdit = QLineEdit(self.tab_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setMaximumSize(QSize(440, 16777215))

        self.horizontalLayout_4.addWidget(self.lineEdit)

        self.pushButton_3 = QPushButton(self.tab_2)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.horizontalLayout_4.addWidget(self.pushButton_3)

        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setEnabled(True)
        self.label_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_6.setTextFormat(Qt.TextFormat.PlainText)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_6)


        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.pushButton_7 = QPushButton(self.tab_2)
        self.pushButton_7.setObjectName(u"pushButton_7")

        self.verticalLayout.addWidget(self.pushButton_7)

        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")

        self.verticalLayout.addWidget(self.label_4)

        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")

        self.verticalLayout.addWidget(self.label_5)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")

        self.horizontalLayout_2.addWidget(self.label_9)

        self.lineEdit_2 = QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")

        self.horizontalLayout_2.addWidget(self.lineEdit_2)

        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")

        self.horizontalLayout_2.addWidget(self.label_11)

        self.lineEdit_4 = QLineEdit(self.tab_2)
        self.lineEdit_4.setObjectName(u"lineEdit_4")

        self.horizontalLayout_2.addWidget(self.lineEdit_4)

        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")

        self.horizontalLayout_2.addWidget(self.label_10)

        self.lineEdit_3 = QLineEdit(self.tab_2)
        self.lineEdit_3.setObjectName(u"lineEdit_3")

        self.horizontalLayout_2.addWidget(self.lineEdit_3)

        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")

        self.horizontalLayout_2.addWidget(self.label_12)

        self.lineEdit_5 = QLineEdit(self.tab_2)
        self.lineEdit_5.setObjectName(u"lineEdit_5")

        self.horizontalLayout_2.addWidget(self.lineEdit_5)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.pushButton_4 = QPushButton(self.tab_2)
        self.pushButton_4.setObjectName(u"pushButton_4")

        self.verticalLayout.addWidget(self.pushButton_4)

        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")

        self.verticalLayout.addWidget(self.label_13)

        self.tableWidget = QTableWidget(self.tab_2)
        self.tableWidget.setObjectName(u"tableWidget")

        self.verticalLayout.addWidget(self.tableWidget)

        self.tabWidget.addTab(self.tab_2, "")

        self.horizontalLayout.addWidget(self.tabWidget)


        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u65e0\u754f\u5951\u7ea6HUD v1.2.0", None))
        self.label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-weight:700;\">\u8fd0\u884c\u8981\u6c42\uff1a\u6e38\u620f\u9700\u4ee5\u3010\u7a97\u53e3\u5316(\u6709\u8fb9\u6846)\u3011\u8fd0\u884c\uff0c\u652f\u6301\u7684\u5206\u8fa8\u7387\u4e3a1920*1080\u62161280*720\uff1b</span></p><p><span style=\" font-weight:700;\">\u672c\u7a0b\u5e8f\u7684\u6587\u4ef6\u8def\u5f84\u5fc5\u987b\u4e3a\u5168\u82f1\u6587\u8def\u5f84\u3002</span></p><p><span style=\" font-weight:700;\">\u8f6f\u4ef6\u514d\u8d39\u4e0b\u8f7d\u4f7f\u7528\uff0c\u552f\u4e00\u4f5c\u8005\u8bf7\u641c\u7d22B\u7ad9up\u4e3b\u201c\u4e36\u6155\u90b5\u201d</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u9009\u62e9\u6e38\u620f\u8fdb\u7a0b\u7a97\u53e3", None))
        self.pushButton_5.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb\u8bfb\u53d6\u8ba1\u5206\u677f", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"TAB\u952e\u5237\u65b0", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u8ba1\u5206\u677f\u9884\u89c8", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"1\u53f7\u73a9\u5bb6", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"6\u53f7\u73a9\u5bb6", None))
        self.comboBox_15.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_15.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_15.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_15.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_15.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_15.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_15.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_15.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_15.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_15.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_15.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_15.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_15.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_15.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_15.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_15.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_15.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_15.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_15.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_15.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_15.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_15.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_15.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_15.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_15.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_15.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_15.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_15.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_15.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.comboBox_16.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_16.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_16.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_16.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_16.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_16.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_16.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_16.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_16.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_16.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_16.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_16.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_16.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_16.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_16.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_16.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_16.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_16.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_16.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_16.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_16.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_16.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_16.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_16.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_16.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_16.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_16.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_16.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_16.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.label_19.setText(QCoreApplication.translate("Form", u"2\u53f7\u73a9\u5bb6", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"7\u53f7\u73a9\u5bb6", None))
        self.comboBox_19.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_19.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_19.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_19.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_19.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_19.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_19.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_19.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_19.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_19.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_19.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_19.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_19.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_19.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_19.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_19.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_19.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_19.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_19.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_19.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_19.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_19.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_19.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_19.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_19.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_19.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_19.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_19.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_19.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.comboBox_20.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_20.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_20.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_20.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_20.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_20.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_20.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_20.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_20.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_20.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_20.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_20.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_20.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_20.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_20.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_20.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_20.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_20.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_20.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_20.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_20.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_20.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_20.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_20.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_20.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_20.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_20.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_20.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_20.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.label_21.setText(QCoreApplication.translate("Form", u"3\u53f7\u73a9\u5bb6", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"8\u53f7\u73a9\u5bb6", None))
        self.comboBox_21.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_21.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_21.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_21.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_21.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_21.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_21.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_21.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_21.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_21.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_21.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_21.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_21.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_21.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_21.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_21.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_21.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_21.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_21.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_21.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_21.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_21.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_21.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_21.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_21.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_21.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_21.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_21.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_21.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.comboBox_22.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_22.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_22.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_22.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_22.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_22.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_22.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_22.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_22.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_22.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_22.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_22.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_22.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_22.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_22.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_22.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_22.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_22.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_22.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_22.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_22.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_22.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_22.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_22.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_22.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_22.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_22.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_22.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_22.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.label_25.setText(QCoreApplication.translate("Form", u"4\u53f7\u73a9\u5bb6", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"9\u53f7\u73a9\u5bb6", None))
        self.comboBox_23.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_23.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_23.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_23.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_23.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_23.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_23.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_23.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_23.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_23.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_23.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_23.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_23.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_23.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_23.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_23.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_23.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_23.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_23.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_23.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_23.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_23.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_23.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_23.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_23.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_23.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_23.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_23.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_23.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.comboBox_24.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_24.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_24.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_24.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_24.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_24.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_24.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_24.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_24.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_24.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_24.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_24.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_24.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_24.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_24.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_24.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_24.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_24.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_24.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_24.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_24.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_24.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_24.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_24.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_24.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_24.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_24.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_24.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_24.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.label_27.setText(QCoreApplication.translate("Form", u"5\u53f7\u73a9\u5bb6", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"10\u53f7\u73a9\u5bb6", None))
        self.comboBox_25.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_25.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_25.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_25.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_25.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_25.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_25.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_25.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_25.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_25.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_25.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_25.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_25.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_25.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_25.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_25.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_25.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_25.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_25.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_25.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_25.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_25.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_25.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_25.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_25.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_25.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_25.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_25.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_25.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.comboBox_26.setItemText(0, QCoreApplication.translate("Form", u"\u8587\u4e1d Vyse", None))
        self.comboBox_26.setItemText(1, QCoreApplication.translate("Form", u"\u94a2\u9501 Deadlock", None))
        self.comboBox_26.setItemText(2, QCoreApplication.translate("Form", u"\u5c1a\u52c3\u52d2 Chamber", None))
        self.comboBox_26.setItemText(3, QCoreApplication.translate("Form", u"\u5947\u4e50 Killjoy", None))
        self.comboBox_26.setItemText(4, QCoreApplication.translate("Form", u"\u96f6 Cypher", None))
        self.comboBox_26.setItemText(5, QCoreApplication.translate("Form", u"\u8d24\u8005 Sage", None))
        self.comboBox_26.setItemText(6, QCoreApplication.translate("Form", u"\u76d6\u53ef Gekko", None))
        self.comboBox_26.setItemText(7, QCoreApplication.translate("Form", u"\u9ed1\u68a6 Fade", None))
        self.comboBox_26.setItemText(8, QCoreApplication.translate("Form", u"K/O KAY/O", None))
        self.comboBox_26.setItemText(9, QCoreApplication.translate("Form", u"\u4e1d\u51ef Skye", None))
        self.comboBox_26.setItemText(10, QCoreApplication.translate("Form", u"\u94c1\u81c2 Breach", None))
        self.comboBox_26.setItemText(11, QCoreApplication.translate("Form", u"\u730e\u67ad Sova", None))
        self.comboBox_26.setItemText(12, QCoreApplication.translate("Form", u"\u66ae\u8776 Clove", None))
        self.comboBox_26.setItemText(13, QCoreApplication.translate("Form", u"\u6d77\u795e Harbor", None))
        self.comboBox_26.setItemText(14, QCoreApplication.translate("Form", u"\u661f\u7908 Astra", None))
        self.comboBox_26.setItemText(15, QCoreApplication.translate("Form", u"\u5e7d\u5f71 Omen", None))
        self.comboBox_26.setItemText(16, QCoreApplication.translate("Form", u"\u8770\u86c7 Viper", None))
        self.comboBox_26.setItemText(17, QCoreApplication.translate("Form", u"\u70bc\u72f1 Brimstone", None))
        self.comboBox_26.setItemText(18, QCoreApplication.translate("Form", u"\u58f9\u51b3 Iso", None))
        self.comboBox_26.setItemText(19, QCoreApplication.translate("Form", u"\u9713\u8679 Neon", None))
        self.comboBox_26.setItemText(20, QCoreApplication.translate("Form", u"\u591c\u9732 Yoru", None))
        self.comboBox_26.setItemText(21, QCoreApplication.translate("Form", u"\u96f7\u5179 Raze", None))
        self.comboBox_26.setItemText(22, QCoreApplication.translate("Form", u"\u82ae\u5a1c Reyna", None))
        self.comboBox_26.setItemText(23, QCoreApplication.translate("Form", u"\u4e0d\u6b7b\u9e1f Phoenix", None))
        self.comboBox_26.setItemText(24, QCoreApplication.translate("Form", u"\u6377\u98ce Jett", None))
        self.comboBox_26.setItemText(25, QCoreApplication.translate("Form", u"\u8ff7\u6838 Miks", None))
        self.comboBox_26.setItemText(26, QCoreApplication.translate("Form", u"\u949b\u72d0 Waylay", None))
        self.comboBox_26.setItemText(27, QCoreApplication.translate("Form", u"\u5e7b\u68f1 Tejo", None))
        self.comboBox_26.setItemText(28, QCoreApplication.translate("Form", u"\u7981\u706d Veto", None))

        self.pushButton_11.setText(QCoreApplication.translate("Form", u"\u786e\u8ba4\u65e0\u8bef\u540e\u5f00\u59cb\u53d1\u9001\u6570\u636e", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-weight:700;\">\u672a\u5f00\u59cb\u53d1\u9001</span></p></body></html>", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-weight:700;\">\u672a\u5f00\u59cb\u8bc6\u522b</span></p></body></html>", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u5e27\u5904\u7406\uff1a-- | \u5e73\u5747\uff1a--", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"\u4f5c\u4e3a\u53d1\u9001\u7aef", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u53d1\u9001\u7aef\u5730\u5740", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u8fde\u63a5", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u672a\u8fde\u63a5", None))
        self.pushButton_7.setText(QCoreApplication.translate("Form", u"\u542f\u52a8HUD\u8986\u76d6\u5c42", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u5e27\u95f4\u9694\uff1a-- | \u5e73\u5747\uff1a-- | \u5df2\u63a5\u65360\u5e27", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u8bbe\u7f6eHUD\u5e03\u5c40", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u5de6\u53f3\u8ddd\u79bb", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u7f29\u653e\u5927\u5c0f", None))
        self.lineEdit_4.setText("")
        self.label_10.setText(QCoreApplication.translate("Form", u"\u884c\u95f4\u9699", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"\u5e95\u90e8\u8ddd\u79bb", None))
        self.lineEdit_5.setText("")
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"\u6539\u53d8\u6587\u672c\u6837\u5f0f", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"\u6570\u636e\u9884\u89c8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"\u4f5c\u4e3a\u63a5\u6536\u7aef", None))
    # retranslateUi

